// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgk4NCBe3tctas6BVDEqvnsjXmXitxgQo',
    appId: '1:407743437613:web:9c578f4ab8fdfc6b6991a4',
    messagingSenderId: '407743437613',
    projectId: 'flutter-bakaiti-app',
    authDomain: 'flutter-bakaiti-app.firebaseapp.com',
    storageBucket: 'flutter-bakaiti-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFuI9jHBhaDhS0LDWeGY8XJmz4mZqvo2s',
    appId: '1:407743437613:android:5652e7c94cd5cb896991a4',
    messagingSenderId: '407743437613',
    projectId: 'flutter-bakaiti-app',
    storageBucket: 'flutter-bakaiti-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFV84r7FMWMieKiiw8PLdhQv_huW5ucyk',
    appId: '1:407743437613:ios:b53c35b028a0ba0b6991a4',
    messagingSenderId: '407743437613',
    projectId: 'flutter-bakaiti-app',
    storageBucket: 'flutter-bakaiti-app.firebasestorage.app',
    androidClientId: '407743437613-ojpm57nk3bik36q8j8ltfj17fdolc0mp.apps.googleusercontent.com',
    iosClientId: '407743437613-7temrtfvrp7aautmojslu9pl7e5tv653.apps.googleusercontent.com',
    iosBundleId: 'com.example.bakaitiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFV84r7FMWMieKiiw8PLdhQv_huW5ucyk',
    appId: '1:407743437613:ios:b53c35b028a0ba0b6991a4',
    messagingSenderId: '407743437613',
    projectId: 'flutter-bakaiti-app',
    storageBucket: 'flutter-bakaiti-app.firebasestorage.app',
    iosBundleId: 'com.example.bakaitiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgk4NCBe3tctas6BVDEqvnsjXmXitxgQo',
    appId: '1:407743437613:web:fcb1e3686857583f6991a4',
    messagingSenderId: '407743437613',
    projectId: 'flutter-bakaiti-app',
    authDomain: 'flutter-bakaiti-app.firebaseapp.com',
    storageBucket: 'flutter-bakaiti-app.firebasestorage.app',
  );
}